<?php
/* Copyright (C) 2026 SuperAdmin */

/**
 *  * \file    custom/doliagropass/core/modules/doliagropass/api_doliagropass.class.php
 *   * \ingroup doliagropass
 *    * \brief   DoliAgroPass External API
 *     */

// 1. Caricamento dipendenze API Dolibarr (QUI È CORRETTO)
// require_once DOL_DOCUMENT_ROOT . '/core/lib/functions.lib.php';
// require_once DOL_DOCUMENT_ROOT . '/core/lib/date.lib.php';
// require_once DOL_DOCUMENT_ROOT . '/api/class/api.class.php';
//
// // 2. Caricamento Classi Modulo
// // Usa un percorso sicuro. Se non trova i file, l'API darà errore 500 ma non sparirà dall'Explorer.
// dol_include_once('/doliagropass/class/doliagropassaudit.class.php');
// dol_include_once('/doliagropass/class/doliagropassindicator.class.php');
//
// /**
//  * API Class for DoliAgroPass module
//   * * ATTENZIONE AL NOME: Deve essere Api + NomeModulo (tutto minuscolo se il file è minuscolo)
//    */
//    class ApiDoliagropass
//    {
//        /** @var DoliDB Database handler */
//            public $db;
//
//                /**
//                     * Constructor
//                          * @param   DoliDB  $db     Database handler
//                               */
//                                   public function __construct(DoliDB $db)
//                                       {
//                                               $this->db = $db;
//                                                   }
//
//                                                       /**
//                                                            * Test API Connection (Ping)
//                                                                 * * @return string
//                                                                      * @url GET /ping
//                                                                           */
//                                                                               public function ping() {
//                                                                                       return "Pong! DoliAgroPass API is working correctly.";
//                                                                                           }
//
//                                                                                               /**
//                                                                                                    * Get a list of Audits (Filtered for PWA Sync)
//                                                                                                         *
//                                                                                                              * @param string $sortfield     Sort field
//                                                                                                                   * @param string $sortorder     Sort order
//                                                                                                                        * @param int    $limit         Limit
//                                                                                                                             * @param int    $page          Page
//                                                                                                                                  * @param string $sqlfilters    SQL filters
//                                                                                                                                       * @return array                List of audit objects
//                                                                                                                                            *
//                                                                                                                                                 * @url GET /audits
//                                                                                                                                                      */
//                                                                                                                                                          public function index($sortfield = "t.rowid", $sortorder = 'ASC', $limit = 100, $page = 0, $sqlfilters = '')
//                                                                                                                                                              {
//                                                                                                                                                                      if (!DolibarrApiAccess::$user->rights->doliagropass->doliagropassaudit->read) {
//                                                                                                                                                                                  throw new RestException(403);
//                                                                                                                                                                                          }
//
//                                                                                                                                                                                                  $obj = new DoliAgroPassAudit($this->db);
//                                                                                                                                                                                                          $list = $obj->fetchAll($sortorder, $sortfield, $limit, $page, $sqlfilters);
//
//                                                                                                                                                                                                                  if ($list < 0) {
//                                                                                                                                                                                                                              throw new RestException(503, 'Error retrieving audit list: ' . implode(',', $obj->errors));
//                                                                                                                                                                                                                                      }
//
//                                                                                                                                                                                                                                              $result = array();
//                                                                                                                                                                                                                                                      foreach ($list as $audit) {
//                                                                                                                                                                                                                                                                  if ($audit->fk_soc > 0) {
//                                                                                                                                                                                                                                                                                  $audit->fetch_thirdparty();
//                                                                                                                                                                                                                                                                                                  $audit->thirdparty_name = $audit->thirdparty->name;
//                                                                                                                                                                                                                                                                                                              }
//                                                                                                                                                                                                                                                                                                                          $result[] = $this->_cleanObject($audit);
//                                                                                                                                                                                                                                                                                                                                  }
//
//                                                                                                                                                                                                                                                                                                                                          return $result;
//                                                                                                                                                                                                                                                                                                                                              }
//
//                                                                                                                                                                                                                                                                                                                                                  /**
//                                                                                                                                                                                                                                                                                                                                                       * Get Full Audit Data
//                                                                                                                                                                                                                                                                                                                                                            *
//                                                                                                                                                                                                                                                                                                                                                                 * @param int $id   ID of Audit
//                                                                                                                                                                                                                                                                                                                                                                      * @return array    Audit object with enriched lines
//                                                                                                                                                                                                                                                                                                                                                                           *
//                                                                                                                                                                                                                                                                                                                                                                                * @url GET /audits/{id}/full
//                                                                                                                                                                                                                                                                                                                                                                                     */
//                                                                                                                                                                                                                                                                                                                                                                                         public function getAuditFull($id)
//                                                                                                                                                                                                                                                                                                                                                                                             {
//                                                                                                                                                                                                                                                                                                                                                                                                     global $langs;
//
//                                                                                                                                                                                                                                                                                                                                                                                                             if (!DolibarrApiAccess::$user->rights->doliagropass->doliagropassaudit->read) {
//                                                                                                                                                                                                                                                                                                                                                                                                                         throw new RestException(403);
//                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                         $audit = new DoliAgroPassAudit($this->db);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                 $result = $audit->fetch($id);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                         if ($result <= 0) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                     throw new RestException(404, 'Audit not found');
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $audit->fetchLines();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $enriched_lines = array();
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (is_array($audit->lines)) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 foreach ($audit->lines as $line) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $ui_options = array();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (!empty($line->input_params)) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $raw_params = json_decode($line->input_params, true);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (is_array($raw_params)) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 foreach ($raw_params as $key => $translationKey) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $ui_options[] = array(
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'value' => $key,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'label' => $langs->trans($translationKey) 
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         );
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $line->ui_options = $ui_options;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $line->label_translated = $langs->trans($line->label);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $line->category_group_translated = $langs->trans($line->category_group);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $enriched_lines[] = $this->_cleanObject($line);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $audit->lines = $enriched_lines;
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if ($audit->fk_soc > 0) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $audit->fetch_thirdparty();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $audit->thirdparty_name = $audit->thirdparty->name;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $audit->thirdparty_address = $audit->thirdparty->address;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         $audit->thirdparty_zip = $audit->thirdparty->zip;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $audit->thirdparty_town = $audit->thirdparty->town;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return $this->_cleanObject($audit);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             /**
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * Update Audit Lines
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       *
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * @param int   $id     ID of Audit
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @param array $lines  Array of line objects
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * @return array        Updated Audit Object
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           *
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @url PUT /audits/{id}/lines
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         public function updateAuditLines($id, $lines)
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (!DolibarrApiAccess::$user->rights->doliagropass->doliagropassaudit->write) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 throw new RestException(403);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $audit = new DoliAgroPassAudit($this->db);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if ($audit->fetch($id) <= 0) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     throw new RestException(404, 'Audit not found');
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (!is_array($lines)) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 throw new RestException(400, 'Invalid data format');
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 foreach ($lines as $lineData) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (empty($lineData['rowid'])) continue;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         $lineObj = new DoliAgroPassAuditLine($this->db);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if ($lineObj->fetch($lineData['rowid']) > 0) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if ($lineObj->fk_audit != $id) continue;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (isset($lineData['value_measured'])) $lineObj->value_measured = $lineData['value_measured'];
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (isset($lineData['score_override'])) $lineObj->score_override = $lineData['score_override'];
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (isset($lineData['note_auditor']))   $lineObj->note_auditor = $lineData['note_auditor'];
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (isset($lineData['score_calc']))     $lineObj->score_calc = $lineData['score_calc'];
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $lineObj->update(DolibarrApiAccess::$user);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 require_once DOL_DOCUMENT_ROOT . '/custom/doliagropass/class/AgroScoreCalculator.class.php';
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         $calculator = new AgroScoreCalculator($this->db);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $calculator->calculateGlobalScore($id);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return $this->getAuditFull($id);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 private function _cleanObject($object)
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $object = (array) $object;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     unset($object['db'], $object['error'], $object['errors'], $object['lines'], $object['model_pdf'], $object['last_main_doc']);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return $object;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
